### ISSUE TITLE
Error in `npm run build`

### ISSUE THREAD

**Issue by rafaeljusto** [techfort/redisvue#1]
I got the following error message when running `npm run build`:

```
Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redisvue@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redisvue@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/teamwork/.npm/_logs/2018-12-05T11_15_05_295Z-debug.log
```

**Comment by techfort** [comment]
hi @rafaeljusto thanks for the feedback! yeah i was using electron to handle window functions (maximize, minimize etc) but electron-builder requires `electron` to be in devDependencies not dependencies, so i found a workaround that does not involved importing electron in the renderer, should be good on master now. Appveyor builds successfully so all should be good, but let me know!

**Comment by techfort** [comment]
@rafaeljusto just tried a release today and all is working well, `electron` is only in devDeps now so closing this.

**Comment by rafaeljusto** [comment]
Thanks @techfort ! 😄

**Comment by janainafortunato** [comment]
Gente boa noite!
Estou tentando gera a pasta dist para roda o  projeto e está dando esse erro. Alguém poderia mim ajuda! Obrigada. 

jana@janaina-PRESARIO-CQ-23:~/trabalho/circoshow-app$ npm run electron-build
npm ERR! missing script: electron-build
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     electron:mac
npm ERR!     electron:linux
npm ERR!     electron:local

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jana/.npm/_logs/2019-06-04T23_32_06_782Z-debug.log

**Comment by rafaeljusto** [comment]
> Estou tentando gera a pasta dist para roda o projeto e está dando esse erro. Alguém poderia mim ajuda! Obrigada.

Translating 😄  _I'm trying to generate the dist directory to run the project but it gives an error. Someone could help me? Thank you._

English: Hey @janainafortunato , to just run the app you can type `npm i`, or if you want to built it you can type `npm run build`. I don't think the option `npm run electron-build` is available.

Portuguese: Olá @janainafortunato , para apenas rodar a aplicação você pode digitar `npm i`, ou construir o projeto com o comando `npm run build`. O comando `npm run electron-build` não parece estar disponível.

**Comment by techfort** [comment]
@rafaeljusto thanks for jumping in bud! i am in italy on holiday atm, and my portuguese is crap at best :)
