### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by itamarhaber** [techfort/redisvue#3]
Hello dear author,

This looks awesome - I'd love to see it become a full-blown Redis thingy. However, before I even clone and try this, I must know what license this project is released under. Would you be able to help with this?

**Comment by techfort** [comment]
@itamarhaber thank you for highlighting this, my bad. I added a MIT license to the project, hope this helps.

**Comment by itamarhaber** [comment]
@techfort - perfect resolution :)

**Comment by techfort** [comment]
@itamarhaber thanks - let me know what you think of it - I got the hang of Vuejs with this project and adding features is actually trivial, so feel free to request for features since I satisfied my needs with this project but I would love if it helped the tons of redis developers out there.
